// Code generated by mockery v2.53.6. DO NOT EDIT.

package ports_mocks

import (
	context "context"

	domain "github.com/charlires/go-base-backend-service/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// PlaylistRepository is an autogenerated mock type for the PlaylistRepository type
type PlaylistRepository struct {
	mock.Mock
}

// AddTrackToPlaylist provides a mock function with given fields: ctx, playlistID, trackID
func (_m *PlaylistRepository) AddTrackToPlaylist(ctx context.Context, playlistID string, trackID string) error {
	ret := _m.Called(ctx, playlistID, trackID)

	if len(ret) == 0 {
		panic("no return value specified for AddTrackToPlaylist")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, playlistID, trackID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePlaylist provides a mock function with given fields: ctx, playlist
func (_m *PlaylistRepository) CreatePlaylist(ctx context.Context, playlist *domain.Playlist) (string, error) {
	ret := _m.Called(ctx, playlist)

	if len(ret) == 0 {
		panic("no return value specified for CreatePlaylist")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Playlist) (string, error)); ok {
		return rf(ctx, playlist)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Playlist) string); ok {
		r0 = rf(ctx, playlist)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Playlist) error); ok {
		r1 = rf(ctx, playlist)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlaylistByID provides a mock function with given fields: ctx, id
func (_m *PlaylistRepository) GetPlaylistByID(ctx context.Context, id string) (*domain.Playlist, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPlaylistByID")
	}

	var r0 *domain.Playlist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Playlist, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Playlist); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Playlist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPlaylistRepository creates a new instance of PlaylistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistRepository {
	mock := &PlaylistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
