// Code generated by mockery v2.53.6. DO NOT EDIT.

package ports_mocks

import (
	context "context"

	domain "github.com/charlires/go-base-backend-service/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// TrackRepository is an autogenerated mock type for the TrackRepository type
type TrackRepository struct {
	mock.Mock
}

// GetTrackByID provides a mock function with given fields: ctx, id
func (_m *TrackRepository) GetTrackByID(ctx context.Context, id string) (*domain.Track, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTrackByID")
	}

	var r0 *domain.Track
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Track, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Track); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Track)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTrackRepository creates a new instance of TrackRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrackRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrackRepository {
	mock := &TrackRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
